[influx]
addr="http://localhost:8086"
username="username"
password="password"

[[accessories]]
name="fast.com"
description="speedtest from fast.com"
unit="MB/s"
query="SELECT LAST(download) FROM speedtest where provider='fast.com'"
database="speedtests"

[[accessories]]
name="speedtest Ø"
description="speedtest mean"
unit="MB/s"
query="SELECT mean(download) FROM speedtest WHERE time > now() - 1h"
database="speedtests"

[homekit]
update=10
name="Dashboard"
pin="12344321"
port="12345"
storage="./db"